### ISSUE TITLE
Question - How did you handle versions of bundled and external pecl packages for a same extension

### ISSUE THREAD

**Issue by llaville** [mlocati/pecl-info#2]
Hello,

I've a question about architecture of this project.
With a recent docker fpm copy of PHP 8.1 beta2 and after installing oci8 extension with https://github.com/mlocati/docker-php-extension-installer, I've noticed that : 

- PECL latest version is 3.0.1
- PHP bundled version is 3.1.0 => see https://github.com/php/php-src/commit/328a07daf5d8d3bc24348ce29c062cce7c4e9a75

And oci8 version installed is of course 3.1.0 (confirmed by command `php --re oci8 | grep version`)

How this WebUI project is supposed to handle such case ?

**Comment by mlocati** [comment]
pecl-info only fetches data from PECL: it doesn't inspect the PHP source code

**Comment by llaville** [comment]
OK and thanks for quick reply !
