### ISSUE TITLE
Typo error on `xpass` extension summary

### ISSUE THREAD

**Issue by llaville** [mlocati/pecl-info#4]
Hello @mlocati 

I've check `xpass` extension today, and found a little typo error on summary : https://github.com/mlocati/pecl-info/blob/main/public/data/summary.json#L22629

It seems not coming from source itself https://github.com/remicollet/php-xpass/blame/master/package.xml or PECL page http://pecl.php.net/package/xpass

**Comment by mlocati** [comment]
@llaville this project doesn't process the PECL package details: they are read directly from the XML files.

I think we should ask @remicollet to fix the source file available at https://pecl.php.net/rest/p/xpass/info.xml

**Comment by remicollet** [comment]
Sorry, but I can't do anything

Perhaps something wrong in rest API (see https://github.com/php/web-pecl)

**Comment by llaville** [comment]
@remicollet ok will check it ASAP

**Comment by llaville** [comment]
REST API gave now the right summary value ! 
I'll close this issue

**Comment by llaville** [comment]
@mlocati Need to rebuild the https://github.com/mlocati/pecl-info/blob/main/public/data/summary.json#L22629 file

**Comment by mlocati** [comment]
> @mlocati Need to rebuild the https://github.com/mlocati/pecl-info/blob/main/public/data/summary.json#L22629 file

@llaville [done](https://github.com/mlocati/pecl-info/commit/011814c0c9a3b63b73789a4f79133187b0a8e98f).
